# OpenAPI / Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/**
springdoc.swagger-ui.api-docs-url=/v3/api-docs

# JWT
security.jwt.secret=${JWT_SECRET:MI_CLAVE_SECRETA_SUPER_LARGA_Y_SEGURA_DE_AL_MENOS_32_CARACTERES}
security.jwt.expiration=86400000

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://root:root2026@cluster1.sozo4ih.mongodb.net/reportes?retryWrites=true&w=majority}

# Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:emailservicio592@gmail.com}
spring.mail.password=${MAIL_PASSWORD:rjew pbdp egpu ymsp}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration